# Generated by Django 5.0.1 on 2024-01-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="cart_item",
            new_name="quantity",
        ),
    ]
