# Generated by Django 5.0.1 on 2024-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(default="PayPal", max_length=100),
            preserve_default=False,
        ),
    ]
