# Generated by Django 5.0.1 on 2024-06-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_payment_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="product_prize",
            new_name="product_price",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
