# Generated by Django 5.0.1 on 2024-06-18 15:32

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderproduct_variation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
