name: Python Linting

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    - name: Check code formatting with Black
      run: |
        black --check .
    - name: Check import order with isort
      run: |
        isort --check-only .
